name: whatsappclone
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  icons_launcher: ^3.0.0                     # For setting app launcher icon in ios and android
  font_awesome_flutter: ^10.5.0              # For using More icons
  google_fonts: 6.2.1                        # For using Google Fonts
  flutter_native_splash: ^2.4.4              # For setting splash screen


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

icons_launcher:
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_maskable: true
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  color: "#F5F5F5"
  image: assets/images/app_icon.png
  branding: assets/images/mysterious_coder_branding_icon.png
  #  color_dark: "#000000"
  #  image_dark: assets/icons/splash_screen.jpg

  android: true
  ios: true
  android_12:
    color: "#F5F5F5"
    image: assets/images/app_icon.png
    branding: assets/images/mysterious_coder_branding_icon.png
#    color_dark: "#000000"
#    image_dark: assets/icons/splash_screen.jpg
