name: expense_app_bloc
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite:
  path_provider:
  path:
  icons_launcher:
  flutter_native_splash:
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#000000"
  image: "assets/images/onboaring_page3.jpg"
  #  branding: "assets/images/ic_mysteriouscoder_branding_logo.png"
  android_12:
    color: "#000000"
    image: "assets/images/onboaring_page3.jpg"
#    branding: "assets/images/ic_mysteriouscoder_branding_logo.png"

icons_launcher:
  image_path: "assets/images/onboaring_page3.jpg"
  adaptive_icon_background: "#000000"
  platforms:
    android:
      enable: true
    ios:
      enable: true

